spring:
  application.name: fraud-detection-engine
#  main:
#    lazy-initialization: true

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 3
      min-spare: 1
    max-connections: 24
    accept-count: 32
