spring:
  application.name: fraud-detection-engine
#  main:
#    lazy-initialization: true

server:
  port: 8080
  servlet:
    context-path: /
  server:
    tomcat:
      threads:
        max: 10-20
        min-spare: 5